"""pyrxmesh -- Python bindings for RXMesh (GPU-accelerated mesh processing)."""

from pyrxmesh._pyrxmesh import Mesh
from pyrxmesh.core import (
    init,
    mesh_info,
    load_obj,
    vertex_normals,
    smooth,
    gaussian_curvature,
    filter,
    mcf,
    geodesic,
    scp,
    param,
    qslim,
    remesh,
    sec,
    delaunay,
    edge_split,
    edge_collapse,
    edge_flip,
    patch_info,
    PatchData,
    detect_features,
    FeatureData,
    expected_edge_length,
    EdgeLengthData,
    feature_remesh,
    quadwild_preprocess,
    quadwild_pipeline,
    vcg_remesh,
)

__version__ = "0.1.0"
__all__ = [
    "Mesh",
    "init",
    "mesh_info",
    "load_obj",
    "vertex_normals",
    "smooth",
    "gaussian_curvature",
    "filter",
    "mcf",
    "geodesic",
    "scp",
    "param",
    "qslim",
    "remesh",
    "sec",
    "delaunay",
    "edge_split",
    "edge_collapse",
    "edge_flip",
    "patch_info",
    "PatchData",
    "detect_features",
    "FeatureData",
    "expected_edge_length",
    "EdgeLengthData",
    "feature_remesh",
    "quadwild_preprocess",
    "quadwild_pipeline",
    "vcg_remesh",
    "__version__",
]
